"""Initial schema

Revision ID: 8647608d93b3
Revises: 
Create Date: 2025-12-17 00:32:06.214494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8647608d93b3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Hashed password using bcrypt/argon2; never store plaintext.'),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=30), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('accept_terms', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('community_posts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('community_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_community_posts_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_posts_id'), ['id'], unique=True)

    op.create_table('crop_disease_detections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('detected_disease', sa.String(length=255), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crop_disease_detections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crop_disease_detections_id'), ['id'], unique=True)
        batch_op.create_index(batch_op.f('ix_crop_disease_detections_user_id'), ['user_id'], unique=False)

    op.create_table('crop_planting_schedules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('crop_name', sa.String(length=100), nullable=False),
    sa.Column('sowing_date', sa.Date(), nullable=False),
    sa.Column('harvest_date_est', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crop_planting_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crop_planting_schedules_id'), ['id'], unique=True)
        batch_op.create_index(batch_op.f('ix_crop_planting_schedules_user_id'), ['user_id'], unique=False)

    op.create_table('crop_soil_analysis',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('ph_level', sa.Float(), nullable=True),
    sa.Column('nitrogen', sa.Float(), nullable=True),
    sa.Column('phosphorus', sa.Float(), nullable=True),
    sa.Column('potassium', sa.Float(), nullable=True),
    sa.Column('moisture', sa.Float(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crop_soil_analysis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crop_soil_analysis_id'), ['id'], unique=True)
        batch_op.create_index(batch_op.f('ix_crop_soil_analysis_user_id'), ['user_id'], unique=False)

    op.create_table('dealers',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('dealers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dealers_user_id'), ['user_id'], unique=True)

    op.create_table('farmers',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('farm_size', sa.Float(), nullable=True, comment='Size in acres/hectares'),
    sa.Column('main_crops', sa.String(length=255), nullable=True, comment='Comma separated crops'),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('farmers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_farmers_user_id'), ['user_id'], unique=True)

    op.create_table('products',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('dealer_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['dealer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_dealer_id'), ['dealer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_id'), ['id'], unique=True)
        batch_op.create_index(batch_op.f('ix_products_name'), ['name'], unique=False)

    op.create_table('community_comments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('community_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_community_comments_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_comments_id'), ['id'], unique=True)
        batch_op.create_index(batch_op.f('ix_community_comments_post_id'), ['post_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_community_comments_post_id'))
        batch_op.drop_index(batch_op.f('ix_community_comments_id'))
        batch_op.drop_index(batch_op.f('ix_community_comments_author_id'))

    op.drop_table('community_comments')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_name'))
        batch_op.drop_index(batch_op.f('ix_products_id'))
        batch_op.drop_index(batch_op.f('ix_products_dealer_id'))
        batch_op.drop_index(batch_op.f('ix_products_category'))

    op.drop_table('products')
    with op.batch_alter_table('farmers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_farmers_user_id'))

    op.drop_table('farmers')
    with op.batch_alter_table('dealers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dealers_user_id'))

    op.drop_table('dealers')
    with op.batch_alter_table('crop_soil_analysis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crop_soil_analysis_user_id'))
        batch_op.drop_index(batch_op.f('ix_crop_soil_analysis_id'))

    op.drop_table('crop_soil_analysis')
    with op.batch_alter_table('crop_planting_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crop_planting_schedules_user_id'))
        batch_op.drop_index(batch_op.f('ix_crop_planting_schedules_id'))

    op.drop_table('crop_planting_schedules')
    with op.batch_alter_table('crop_disease_detections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crop_disease_detections_user_id'))
        batch_op.drop_index(batch_op.f('ix_crop_disease_detections_id'))

    op.drop_table('crop_disease_detections')
    with op.batch_alter_table('community_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_community_posts_id'))
        batch_op.drop_index(batch_op.f('ix_community_posts_author_id'))

    op.drop_table('community_posts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_phone'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
